version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    user: root
    networks:
      - jenkins-network

  docker-dind:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
    networks:
      - jenkins-network

volumes:
  jenkins_home:
  docker-certs-ca:
  docker-certs-client:

networks:
  jenkins-network:
    driver: bridge

